Bug fixes + SPM option to show mask
glatard/livingpark-utils pull request #1
Opened 2022-09-17 22:28 UTC by mohanadarafe

2022-09-20 14:17 UTC, glatard requested changes
Thanks for doing this @mohanadarafe, see my comments inline. Please also make sure to run `pre-commit run --all` before committing.

2022-09-20 14:17 UTC, glatard commented on livingpark_utils/livingpark_utils.py
> +        show_gm: bool,
please add default values and documentation for these parameters.

2022-09-20 14:17 UTC, glatard commented on livingpark_utils/livingpark_utils.py
> +            output_file_c2 = output_file_name.replace("PPMI", "c2PPMI", 1)
This should be conditional to the use of mni_space=False

2022-09-20 14:17 UTC, glatard commented on livingpark_utils/livingpark_utils.py
> +
The logic is not right: when showing in MNI space then anat_image is not shown (anat_image is in native space). Or else, use normalized anat_image. In addition, show_gm and show_wm should work wheter in mni_space or in native space.

2022-09-20 14:17 UTC, glatard commented on livingpark_utils/livingpark_utils.py
> +    def qc_spm_segmentations(self, cohort, mni_space = False, show_gm = False, show_wm = False, cut_coords=(-28, -7, 17)) -> None:
default values should be all set to True. With the current default values, nothing is displayed.

2022-09-20 14:56 UTC, mohanadarafe commented
HI @glatard thank you for the comments, I have updated the PR accordingly.

2022-09-21 00:26 UTC, glatard approved these changes

2022-10-08 00:11 UTC, merged